### ISSUE TITLE
EZAudioFile EXC_BAD_ACCESS

### ISSUE THREAD

**Issue by WanFengJun** [syedhali/EZAudio#80]
I often got EXC_BAD_ACCESS in playback just recored audio.
![screen shot 2014-08-21 at 2 27 40 am](https://cloud.githubusercontent.com/assets/5952923/3986121/6df79ec8-2898-11e4-948d-bee7c38d6fbc.png)

**Comment by syedhali** [comment]
This has since been fixed in the 0.3.0 release where read/seek operations are wrapped in a mutex lock. The [EZAudioPlayFileExample](https://github.com/syedhali/EZAudio/tree/master/EZAudioExamples/iOS/EZAudioPlayFileExample) includes a continuous slider for the play position that now doesn't crash when reading/seeking quickly on different threads.
